export const languageNames: Record<string, Record<string, string>> = {
  en: {
    en: "English",
    es: "Spanish",
    de: "German",
    fr: "French",
    hi: "Hindi",
    ja: "Japanese",
  },
  es: {
    en: "Inglés",
    es: "Español",
    de: "Alemán",
    fr: "Francés",
    hi: "Hindi",
    ja: "Japonés",
  },
  de: {
    en: "Englisch",
    es: "Spanisch",
    de: "Deutsch",
    fr: "Französisch",
    hi: "Hindi",
    ja: "Japanisch",
  },
  fr: {
    en: "Anglais",
    es: "Espagnol",
    de: "Allemand",
    fr: "Français",
    hi: "Hindi",
    ja: "Japonais",
  },
  hi: {
    en: "अंग्रेज़ी",
    es: "स्पेनिश",
    de: "जर्मन",
    fr: "फ्रेंच",
    hi: "हिंदी",
    ja: "जापानी",
  },
  ja: {
    en: "英語",
    es: "スペイン語",
    de: "ドイツ語",
    fr: "フランス語",
    hi: "ヒンディー語",
    ja: "日本語",
  },
};
